import { Code2, BriefcaseBusiness, Mail, MapPin, ArrowDown } from 'lucide-react'
import { Link } from 'react-router-dom'
import Button from '../components/ui/Button'
import SectionHeading from '../components/ui/SectionHeading'
import ProjectCard from '../components/ui/ProjectCard'
import ExperienceCard from '../components/ui/ExperienceCard'
import { links, skills, experiences, projects, education } from '../data/portfolioData'
export default function Home(){ return <div id="top"><section className="hero container"><div className="hero-copy"><p className="eyebrow">Software Development Engineer Intern · Bengaluru</p><h1>Playful ideas.<br/><em>Solid systems.</em></h1><div className="hero-bottom"><p>Full-stack developer working at the intersection of intelligent products, scalable backend systems, and human-centred interfaces.</p><div className="flex flex-wrap gap-3"><Button href="#projects">View projects</Button><Button href={links.resume} download secondary>Download résumé</Button></div></div></div><div className="hero-portrait"><img src="/images/praneesha-avatar.svg" alt="Illustrated portrait of Bheemarasetty Praneesha"/></div><div className="hero-spark spark-one" aria-hidden="true">✧</div><div className="hero-spark spark-two" aria-hidden="true">✦</div><a href="#about" className="scroll-cue">Scroll to explore <ArrowDown size={16}/></a></section>
<section id="about" className="section container grid gap-10 border-t border-ink/15 pt-20 md:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="01 / About" title="A curious builder with a practical streak."/><div className="max-w-xl text-lg leading-8 text-ink/70"><p>I’m Praneesha, a Software Development Engineer Intern focused on creating useful experiences from the frontend through to the data layer.</p><p className="mt-5">My work spans React interfaces, Java and Node.js backends, and AI-powered retrieval systems. I enjoy making complex technology feel clear, reliable, and genuinely useful.</p></div></section>
<section id="skills" className="section tinted"><div className="container"><SectionHeading eyebrow="02 / Capabilities" title="Tools I reach for." text="A balanced toolkit for building, learning, and shipping."/><div className="grid gap-x-12 md:grid-cols-2">{skills.map(([name,items])=><div key={name} className="skill-row"><h3>{name}</h3><p>{items}</p></div>)}</div></div></section>
<section id="experience" className="section container"><SectionHeading eyebrow="03 / Experience" title="Learning by building in the real world."/><div>{experiences.map((item,index)=><ExperienceCard key={item.company} item={item} index={index}/>)}</div></section>
<section id="projects" className="section project-section"><div className="container"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeading eyebrow="04 / Selected work" title="Projects with a point of view." text="A small selection of work across AI and web experiences."/><Link to="/projects" className="mb-12 text-sm font-bold text-saffron hover:underline">See all project details →</Link></div><div className="grid gap-7 lg:grid-cols-2">{projects.map((project,index)=><ProjectCard key={project.title} project={project} index={index + 1}/>)}</div></div></section>
<section id="education" className="section container"><SectionHeading eyebrow="05 / Education" title="Foundation first." text="A path shaped by steady curiosity, strong fundamentals, and a growing appetite for systems."/><div className="learning-path">{education.map((item,index)=><article key={item.degree} className="learning-stop"><div className="learning-orbit"><span>0{index + 1}</span></div><p className="learning-date">{item.date}</p><h3>{item.degree}</h3><p className="learning-school">{item.school}</p><p className="learning-result">{item.result}</p></article>)}</div></section>
<section id="contact" className="section container"><div className="contact-panel"><p className="eyebrow text-saffron">06 / Contact</p><h2>Let’s build<br/><em>something useful.</em></h2><p>Open to software engineering opportunities, ambitious ideas, and thoughtful collaboration.</p><a className="contact-email" href={`mailto:${links.email}`}><Mail size={20}/>{links.email}</a><div className="flex flex-wrap gap-5 text-sm font-bold"><a href={links.linkedin} target="_blank" rel="noreferrer"><BriefcaseBusiness className="inline mr-1" size={16}/>LinkedIn</a><a href={links.github} target="_blank" rel="noreferrer"><Code2 className="inline mr-1" size={16}/>GitHub</a><span><MapPin className="inline mr-1" size={16}/>Bengaluru, Karnataka</span></div></div></section></div> }
